# Generated by Django 5.0 on 2023-12-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencereason',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
