# Generated by Django 5.0 on 2023-12-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_absencereason_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absencereason',
            name='description',
        ),
    ]
