# Generated by Django 4.2 on 2023-12-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_professor_departament_course_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisestandard',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
