# Generated by Django 4.2 on 2023-12-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_exercisestandard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisestandard',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
