# Generated by Django 4.2 on 2023-12-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_exercisestandard_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
