# Generated by Django 4.2 on 2023-12-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_uniforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestandard',
            name='uniform_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.uniforms'),
        ),
        migrations.AddField(
            model_name='grading',
            name='uniform_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.uniforms'),
        ),
    ]
