# Generated by Django 4.2 on 2023-12-29 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_exercisestandard_uniform_type_grading_uniform_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisestandard',
            name='uniform_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.uniforms'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='grading',
            name='uniform_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.uniforms'),
        ),
        migrations.AlterUniqueTogether(
            name='departament',
            unique_together={('name', 'platoon', 'course')},
        ),
    ]
