# Generated by Django 5.0 on 2023-12-29 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_exercisestandard_uniform_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='img/author.jpg', upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.cadet')),
            ],
        ),
    ]
