# Generated by Django 5.0.1 on 2024-02-08 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cadetprofile'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': 'Отделение'},
        ),
        migrations.AddField(
            model_name='exercisestandard',
            name='koef_down_fine',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='exercisestandard',
            name='koef_up_fine',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='exercisestandard',
            name='value_fine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exercisestandard',
            name='value_great',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exercisestandard',
            name='value_satisfactory',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.departament', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='patronymic',
            field=models.CharField(max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.rank', verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='platoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.platoon', verbose_name='Взвод'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='platoon',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.company', verbose_name='Рота'),
        ),
        migrations.AlterField(
            model_name='platoon',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        )
    ]
