# Generated by Django 5.0.1 on 2024-02-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_koef_down_fine_exercisestandard_koef_down_great_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        )
    ]
