# Generated by Django 5.0.1 on 2024-02-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_leaderdata_old_rate_leaderdata_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderdata',
            name='old_rate',
        )
    ]
