# Generated by Django 5.0.1 on 2024-02-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cadet_photo_delete_cadetprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadet',
            name='photo',
            field=models.ImageField(blank=True, default='static/img/author.jpg', null=True, upload_to='profile_pics/', verbose_name='Фотография'),
        ),
    ]
