# Generated by Django 5.0.1 on 2024-02-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_cadet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestandard',
            name='reverse',
            field=models.BooleanField(default=False),
        ),
    ]
