# Generated by Django 5.0.1 on 2024-03-04 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_unittype'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestandard',
            name='unit_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.unittype'),
        ),
    ]
